spring:
  config:
    activate:
      on-profile: local
    import: 'aws-parameterstore:'
  cloud:
    gateway:
      #      httpclient: # 글로벌 설정
      #        connect-timeout: 5000 # ms
      #        response-timeout: 5s
      routes:
        - id: api-server
          uri: lb://API-SERVER:8082
          predicates:
            - Path=/graphql, /api/v1/**
          filters:
            - name: JwtAuthentication
          #            - args:
          #                baseMessage: My Custom Message
          #                preLogger: true
          #                postLogger: true
          metadata:
            connect-timeout: 5000
            response-timeout: 5000

# ==============================
# = aws
# ==============================
aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: '-'
    name: app-palette
    fail-fast: true

# ===============================
# = eureka
# ===============================
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
