spring:
  main:
    banner-mode: off
    web-application-type: reactive
  application:
    name: gateway-server
  profiles:
    default: local
    group:
      local: local
      dev: dev

# actuator/gateway/routes 경로를 통하여 정보 확인 가능
management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true

# ===============================
# = server config
# ===============================
server:
  port: 8080
