spring:
  config:
    activate:
      on-profile: local
  cloud:
    gateway:
      #      httpclient: # 글로벌 설정
      #        connect-timeout: 5000 # ms
      #        response-timeout: 5s
      routes:
        - id: api-service
          uri: http://localhost:8082
          predicates:
            - Path=/graphql
          filters:
            - name: JwtAuthentication
          #            - args:
          #                baseMessage: My Custom Message
          #                preLogger: true
          #                postLogger: true
          metadata:
            connect-timeout: 5000
            response-timeout: 5000
