spring:
  config:
    activate:
      on-profile: local
    import: 'aws-parameterstore:'
  cloud:
    gateway:
      #      httpclient: # 글로벌 설정
      #        connect-timeout: 5000 # ms
      #        response-timeout: 5s
      routes:
        - id: api-service
          uri: http://localhost:8082
          predicates:
            - Path=/graphql, /v1/**
          filters:
            - name: JwtAuthentication
          #            - args:
          #                baseMessage: My Custom Message
          #                preLogger: true
          #                postLogger: true
          metadata:
            connect-timeout: 5000
            response-timeout: 5000

aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: '-'
    name: app-palette
    fail-fast: true

security:
  jwt:
    access-token:
      secret-key: test
      expire-length: 300000
    refresh-token:
      secret-key: test
      expire-length: 3600000